In [7]:
#1 1부터 10까지(미포함)의 2걸음(step) 크기의 정수값 배열을 생성해보자.

import numpy as np

arr1 = np.arange(1,10,2)
arr1 #print(arr1)

array([1, 3, 5, 7, 9])

In [9]:
#2 모양이 (3,4)인 모든 값이 1인 배열을 생성해보자.

import numpy as np

arr2 = np.ones((3,4))
arr2 #print(arr2)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#3 0과 1사이를 10등분하고자 할 때 등분값 배열을 생성해보자.

import numpy as np

arr3 = np.linspace(0,1,10)   # <--- 이때는 stop -1 만 해당되고 이런건 없는건지...?
arr3   #print(arr3)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
# 1. A행렬을 생성해보자.

A = np.array(
 [[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

print(A)

# 2. A의 모양(shape)을 출력해보자.
print(A.shape)

# 3. 19 값을 추출해보자.
print(A[3,3])

# 4. 슬라이싱을 이용하여 [[1, 2], [6, 7]] 값을 추출해보자   (★어려움)
print(A[0:2,0:2])    #0은 생략가능

# 5. 슬라이싱을 이용하여 [[19, 20], [24, 25]] 값을 추출해보자. (★어려움)
print(A[-2:, -2:])

# 6. 슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출해보자. 0축: (★어려움)  0축이 뭔지...?
print(A[0:2, :])

# 7. 슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자. 1축: 행렬 다 포함(★어려움)
print(A[:, -2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [33]:
# 1. A행렬을 생성해보자.


arr=np.arange(1,37)
arr_3d=arr.reshape(3,3,4)
print(arr_3d)


# 2. A 배열의 모양과 크기를 출력해보자.
print(arr_3d.shape)
print(arr_3d.size)

# 3. A의 모양을 (3, 4, 3)로 변경해보자.
arr_3d=arr.reshape(3,4,3)
print(arr_3d)

# 4. A를 1차원 배열로 구성해보자. flat 명령 쓰기
print(arr_3d.flatten())


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
